development:
  adapter: postgresql
  encoding: unicode
  database: bartell_development
  host: localhost
  username: postgres
  password: password
  template: template0
  pool: 5
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: bartell_test
  host: localhost
  username: postgres
  password: password
  template: template0
  pool: 5
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: bartell_production
  host: localhost
  username: postgres
  password: password
  template: template0
  pool: 5
  min_messages: WARNING