development:
  adapter: postgresql
  encoding: unicode
  database: bartell_development
  host: localhost
  username: postgres
  password: password
  template: template0
  pool: 5
  min_messages: WARNING

test:
  adapter: postgresql
  encoding: unicode
  database: bartell_test
  host: localhost
  username: postgres
  password: password
  template: template0
  pool: 5
  min_messages: WARNING

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: scott_production
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock